# Generated by Django 5.2.14 on 2026-05-25 10:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AditivoAlimentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_quimico', models.CharField(help_text='Ex: Tartrazina, Fosfato de Sódio', max_length=150)),
                ('funcao_tecnologica', models.CharField(help_text='Ex: Corante, Estabilizador, Emulsionante', max_length=100)),
                ('grau_risco', models.CharField(help_text='Ex: Baixo, Médio, Alto', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ConsistenciaFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_textura', models.CharField(help_text='Ex: Líquida, Pastosa, Sólida', max_length=100)),
                ('esforco_mastigatorio', models.CharField(help_text='Ex: Baixo, Moderado, Alto', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LaudoMetabolico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_sintese', models.TextField()),
                ('classe_alerta_css', models.CharField(help_text='Injeta a classe CSS correspondente ao nível de risco cromático', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SimulacaoRefeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_sessao', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data_simulacao', models.DateTimeField(auto_now_add=True)),
                ('peso_total_g', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('categoria_nova', models.CharField(help_text='Ex: NOVA 1 (In Natura), NOVA 4 (Ultraprocessado)', max_length=50)),
                ('energia_kcal', models.FloatField(help_text='Valor energético por porção')),
                ('porcao_g', models.FloatField(help_text='Peso da porção de referência em gramas')),
                ('consistencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.consistenciafisica')),
            ],
        ),
        migrations.CreateModel(
            name='RelatorioExportavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formato_saida', models.CharField(default='HTML', max_length=10)),
                ('laudo_metabolico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exportacoes', to='app.laudometabolico')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreRiscoCardio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontuacao_risco', models.IntegerField(default=0)),
                ('potencial_aterogenico', models.CharField(default='Normal', max_length=100)),
                ('simulacao_refeicao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score_cardio', to='app.simulacaorefeicao')),
            ],
        ),
        migrations.CreateModel(
            name='MarcadorDisbiose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risco_permeabilidade', models.CharField(default='Baixo', max_length=50)),
                ('descricao_alerta', models.TextField(blank=True, default='')),
                ('simulacao_refeicao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marcador_disbiose', to='app.simulacaorefeicao')),
            ],
        ),
        migrations.AddField(
            model_name='laudometabolico',
            name='simulacao_refeicao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='laudo', to='app.simulacaorefeicao'),
        ),
        migrations.CreateModel(
            name='ItemRefeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_g', models.FloatField(help_text='Quantidade inserida no prato pelo usuário')),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.alimento')),
                ('simulacao_refeicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='app.simulacaorefeicao')),
            ],
        ),
        migrations.CreateModel(
            name='CalculoETA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eta_basal_kcal', models.FloatField(default=0.0)),
                ('etapa_final_kcal', models.FloatField(default=0.0)),
                ('percentual_queda', models.FloatField(default=0.0)),
                ('simulacao_refeicao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calculo_eta', to='app.simulacaorefeicao')),
            ],
        ),
        migrations.CreateModel(
            name='SugestaoTroca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alimento_substituto_innatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trocas_como_substituto', to='app.alimento')),
                ('alimento_ultraprocessado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trocas_como_ruim', to='app.alimento')),
            ],
        ),
        migrations.CreateModel(
            name='AlimentoAditivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aditivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.aditivoalimentar')),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.alimento')),
            ],
            options={
                'unique_together': {('alimento', 'aditivo')},
            },
        ),
    ]
