# Generated by Django 5.2.14 on 2026-05-25 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AditivoAlimentar',
            new_name='AditivoAlimentare',
        ),
        migrations.RenameModel(
            old_name='CalculoETA',
            new_name='Calculo',
        ),
        migrations.RenameModel(
            old_name='ItemRefeicao',
            new_name='ItemRefeicoe',
        ),
        migrations.RenameModel(
            old_name='RelatorioExportavel',
            new_name='Relatorio',
        ),
        migrations.RenameModel(
            old_name='ScoreRiscoCardio',
            new_name='RiscoCardiaco',
        ),
        migrations.RenameModel(
            old_name='SimulacaoRefeicao',
            new_name='SimulacaoRefeicoe',
        ),
    ]
