# Generated by Django 5.2.14 on 2026-06-01 12:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_aditivoalimentar_aditivoalimentare_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AditivoAlimentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_quimico', models.CharField(help_text='Ex.: Tartrazina, Fosfato de Sódio', max_length=150, unique=True)),
                ('funcao_tecnologica', models.CharField(help_text='Ex.: Corante, Estabilizador, Emulsionante', max_length=120)),
                ('grau_risco', models.CharField(choices=[('Baixo', 'Baixo'), ('Médio', 'Médio'), ('Alto', 'Alto')], default='Baixo', max_length=20)),
                ('impacto_fisiologico', models.TextField(blank=True, default='Impacto fisiológico não descrito na base. Complete este campo com a evidência usada no projeto.')),
            ],
            options={
                'verbose_name': 'Aditivo alimentar',
                'verbose_name_plural': 'Aditivos alimentares',
                'ordering': ['nome_quimico'],
            },
        ),
        migrations.CreateModel(
            name='SimulacaoRefeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_sessao', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data_simulacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('peso_total_g', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Simulação de refeição',
                'verbose_name_plural': 'Simulações de refeição',
                'ordering': ['-data_simulacao'],
            },
        ),
        migrations.RemoveField(
            model_name='itemrefeicoe',
            name='alimento',
        ),
        migrations.RemoveField(
            model_name='itemrefeicoe',
            name='simulacao_refeicao',
        ),
        migrations.RemoveField(
            model_name='relatorio',
            name='laudo_metabolico',
        ),
        migrations.RemoveField(
            model_name='riscocardiaco',
            name='simulacao_refeicao',
        ),
        migrations.AlterModelOptions(
            name='alimento',
            options={'ordering': ['nome'], 'verbose_name': 'Alimento', 'verbose_name_plural': 'Alimentos'},
        ),
        migrations.AlterModelOptions(
            name='alimentoaditivo',
            options={'ordering': ['alimento__nome', 'aditivo__nome_quimico'], 'verbose_name': 'Associação alimento-aditivo', 'verbose_name_plural': 'Associações alimento-aditivo'},
        ),
        migrations.AlterModelOptions(
            name='consistenciafisica',
            options={'ordering': ['tipo_textura'], 'verbose_name': 'Consistência física', 'verbose_name_plural': 'Consistências físicas'},
        ),
        migrations.AlterModelOptions(
            name='laudometabolico',
            options={'verbose_name': 'Laudo metabólico', 'verbose_name_plural': 'Laudos metabólicos'},
        ),
        migrations.AlterModelOptions(
            name='marcadordisbiose',
            options={'verbose_name': 'Marcador de disbiose', 'verbose_name_plural': 'Marcadores de disbiose'},
        ),
        migrations.AlterModelOptions(
            name='sugestaotroca',
            options={'verbose_name': 'Sugestão de troca', 'verbose_name_plural': 'Sugestões de troca'},
        ),
        migrations.AddField(
            model_name='alimento',
            name='observacao_metabolica',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='alimentoaditivo',
            name='observacao',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='consistenciafisica',
            name='observacao',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sugestaotroca',
            name='justificativa',
            field=models.TextField(blank=True, default='Troca sugerida para reduzir processamento e aditivos críticos.'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='categoria_nova',
            field=models.CharField(choices=[('NOVA 1', 'NOVA 1 - In natura ou minimamente processado'), ('NOVA 2', 'NOVA 2 - Ingrediente culinário processado'), ('NOVA 3', 'NOVA 3 - Processado'), ('NOVA 4', 'NOVA 4 - Ultraprocessado')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='energia_kcal',
            field=models.FloatField(help_text='Valor energético por porção', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='nome',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='porcao_g',
            field=models.FloatField(help_text='Peso da porção de referência em gramas', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='consistenciafisica',
            name='esforco_mastigatorio',
            field=models.CharField(help_text='Ex.: Baixo, Moderado, Alto', max_length=100),
        ),
        migrations.AlterField(
            model_name='consistenciafisica',
            name='tipo_textura',
            field=models.CharField(help_text='Ex.: Líquida, Pastosa, Sólida', max_length=100),
        ),
        migrations.AlterField(
            model_name='laudometabolico',
            name='classe_alerta_css',
            field=models.CharField(default='alert-success', max_length=50),
        ),
        migrations.AlterField(
            model_name='laudometabolico',
            name='texto_sintese',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterUniqueTogether(
            name='sugestaotroca',
            unique_together={('alimento_ultraprocessado', 'alimento_substituto_innatura')},
        ),
        migrations.AddField(
            model_name='alimento',
            name='aditivos',
            field=models.ManyToManyField(blank=True, related_name='alimentos', through='app.AlimentoAditivo', to='app.aditivoalimentar'),
        ),
        migrations.AlterField(
            model_name='alimentoaditivo',
            name='aditivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.aditivoalimentar'),
        ),
        migrations.CreateModel(
            name='RelatorioExportavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formato_saida', models.CharField(default='HTML', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('laudo_metabolico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exportacoes', to='app.laudometabolico')),
            ],
            options={
                'verbose_name': 'Relatório exportável',
                'verbose_name_plural': 'Relatórios exportáveis',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ScoreRiscoCardio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontuacao_risco', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('potencial_aterogenico', models.CharField(default='Não calculado', max_length=120)),
                ('simulacao_refeicao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score_cardio', to='app.simulacaorefeicao')),
            ],
            options={
                'verbose_name': 'Score de risco cardiovascular',
                'verbose_name_plural': 'Scores de risco cardiovascular',
            },
        ),
        migrations.CreateModel(
            name='ItemRefeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_g', models.FloatField(help_text='Quantidade em gramas', validators=[django.core.validators.MinValueValidator(1)])),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.alimento')),
                ('simulacao_refeicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='app.simulacaorefeicao')),
            ],
            options={
                'verbose_name': 'Item da refeição',
                'verbose_name_plural': 'Itens da refeição',
            },
        ),
        migrations.CreateModel(
            name='CalculoETA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eta_basal_kcal', models.FloatField(default=0.0)),
                ('etapa_final_kcal', models.FloatField(default=0.0)),
                ('percentual_queda', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('simulacao_refeicao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calculo_eta', to='app.simulacaorefeicao')),
            ],
            options={
                'verbose_name': 'Cálculo de ETA',
                'verbose_name_plural': 'Cálculos de ETA',
            },
        ),
        migrations.AlterField(
            model_name='laudometabolico',
            name='simulacao_refeicao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='laudo', to='app.simulacaorefeicao'),
        ),
        migrations.AlterField(
            model_name='marcadordisbiose',
            name='simulacao_refeicao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marcador_disbiose', to='app.simulacaorefeicao'),
        ),
        migrations.DeleteModel(
            name='Calculo',
        ),
        migrations.DeleteModel(
            name='ItemRefeicoe',
        ),
        migrations.DeleteModel(
            name='Relatorio',
        ),
        migrations.DeleteModel(
            name='RiscoCardiaco',
        ),
        migrations.DeleteModel(
            name='AditivoAlimentare',
        ),
        migrations.DeleteModel(
            name='SimulacaoRefeicoe',
        ),
    ]
