# Generated by Django 5.2.15 on 2026-06-07 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_aditivoalimentar_simulacaorefeicao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aditivoalimentar',
            options={'ordering': ['nome_quimico'], 'verbose_name': 'Componente do rótulo', 'verbose_name_plural': 'Componentes do rótulo'},
        ),
        migrations.AlterModelOptions(
            name='alimentoaditivo',
            options={'ordering': ['alimento__nome', 'aditivo__nome_quimico'], 'verbose_name': 'Associação alimento-componente', 'verbose_name_plural': 'Associações alimento-componente'},
        ),
        migrations.AlterModelOptions(
            name='calculoeta',
            options={'verbose_name': 'Gasto estimado', 'verbose_name_plural': 'Gastos estimados'},
        ),
        migrations.AlterModelOptions(
            name='laudometabolico',
            options={'verbose_name': 'Resumo da refeição', 'verbose_name_plural': 'Resumos das refeições'},
        ),
        migrations.AlterModelOptions(
            name='marcadordisbiose',
            options={'verbose_name': 'Atenção intestinal', 'verbose_name_plural': 'Atenções intestinais'},
        ),
        migrations.AlterModelOptions(
            name='scoreriscocardio',
            options={'verbose_name': 'Atenção ao coração', 'verbose_name_plural': 'Atenções ao coração'},
        ),
        migrations.AlterField(
            model_name='aditivoalimentar',
            name='impacto_fisiologico',
            field=models.TextField(blank=True, default='Observação ainda não cadastrada.'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='categoria_nova',
            field=models.CharField(choices=[('NOVA 1', 'Mais natural'), ('NOVA 2', 'Ingrediente culinário'), ('NOVA 3', 'Preparado'), ('NOVA 4', 'Mais industrializado')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='sugestaotroca',
            name='justificativa',
            field=models.TextField(blank=True, default='Troca sugerida para reduzir excesso de industrialização.'),
        ),
    ]
